version: '3'
services:
  nginx:
    build: ./scripts/nginx
    ports:
      - 80:80
      - 443:443
    image: 654654343720.dkr.ecr.ap-northeast-2.amazonaws.com/koaza-app:latest
    depends_on:
      - app
    platform: linux/amd64
  app:
    build:
      context: .
      dockerfile: ./scripts/app/Dockerfile
    volumes:
      - ./:/project/code
    command: ["./scripts/docker_compose_command.sh"]
    ports:
      - "8000:8000"
    platform: linux/amd64
    image: 654654343720.dkr.ecr.ap-northeast-2.amazonaws.com/koaza-nginx:latest
    env_file:
      - .env
