"""source_newspaper 추가

Revision ID: e7aa7c867bfc
Revises: 2b6c5a5960bc
Create Date: 2024-04-12 14:04:38.622147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7aa7c867bfc'
down_revision: Union[str, None] = '2b6c5a5960bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_newspaper', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'source_newspaper')
    # ### end Alembic commands ###
